apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2app-deployment
  namespace: lab2ns
  labels:
    app: lab2app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2app
  template:
    metadata:
      labels:
        app: lab2app
    spec:        
      containers:
      - name: lab2-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-cm
              key: ReactAppUserName
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: env-cm
              key: ReactAppCompanyName
